app/src/routes/login_routes.py
import flask
from config import *

app = Flask(__name__)

conexion = MySQL(app)

ingreso = flask.Blueprint('ingreso',__name__)

@ingreso.route('/login', methods=['POST','GET'])
def login():
    if request.method == 'POST':
        usuario = User(0,request.form['username'],request.form['password'])
        usuario_logueado = ModelUser.login(conexion, usuario)
        if usuario_logueado != None:
            if usuario_logueado.password:
                if usuario_logueado.estado_usuario == 1:
                    login_user(usuario_logueado)
                    return redirect(url_for('presentacion'))
                else:
                    flash('Usuario Inactivo')
                    data = { 'titulo': 'Inicio de Sesión' }
                    return render_template('auth/login.html',data=data)
            else:
                flash('Contraseña incorrecta')
                data = { 'titulo': 'Inicio de Sesión' }
                return render_template('auth/login.html',data=data)
        else:
            flash('El usuario no existe')
            data = { 'titulo': 'Inicio de Sesión' }
            return render_template('auth/login.html',data=data)
    else:
        data = { 'titulo': 'Inicio de Sesión' }
        return render_template('auth/login.html',data=data)

@ingreso.route('/logout')
def cerrar_sesion():
    logout_user()
    return redirect(url_for('ingreso.login'))

app/src/templates/cambiar_pass.html
{% extends './layout.html' %}

{% block title %}
    {{data.titulo}}
{% endblock %}

{% block nameuser %}
  {{ current_user.nombre_usuario }}
{% endblock %}

{% block body %}
    
  <form class="w-50 pt-3 m-auto" method="post" action="/editar/pass/{{current_user.id}}" autocomplete="off">
    <legend id="cambiar_pass" class="text-center">Cambiar Contraseña</legend>
    <div class="dropdown-divider"></div>
    {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br>
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif%}
                {% endfor %}
            {% endif %}
        {% endwith %}
      <div class="form-group">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="actual" class="form-label mt-4">Contraseña Actual</label>
        <input type="password" required maxlength="20" class="form-control fs-6" id="actual" name="actual" value="">
        <label for="nueva_pass" class="form-label mt-4">Nueva Contraseña</label>
        <input type="password" required maxlength="20" class="form-control fs-6" id="nueva_pass" name="nueva_pass" value="">
        <label for="repeticion" class="form-label mt-4">Nueva Contraseña</label>
        <input type="password" required maxlength="20" class="form-control fs-6" id="repeticion" name="repeticion" placeholder="Repita la nueva contraseña" value="">
      </div>
      <div class="dropdown-divider mt-4 mb-4"></div>
      <fieldset class="form-group mt-3 mb-3 text-center">
        <button type="submit" class="btn btn-light fs-6 p-3 ps-5 pe-5 w-auto">Cambiar Contraseña</button>
      </fieldset>
  </form>

{% endblock %}

app/src/templates/crear_usuario.html
{% extends './layout.html' %}

{% block title %}
    {{data.titulo}}
{% endblock %}

{% block nameuser %}
  {{ current_user.nombre_usuario }}
{% endblock %}

{% block body %}

<form class="w-50 pt-3 m-auto" method="post" action="/crear/usuario" autocomplete="off">
    <fieldset>
      <legend class="text-center">Registrar Nuevo Usuario</legend>
      <div class="dropdown-divider"></div>
      {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br>
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif%}
                {% endfor %}
            {% endif %}
        {% endwith %}
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="form-group">
        <label for="username" class="form-label mt-4">Usuario</label>
        <input type="number" required maxlength="10" max="9999999999" class="form-control fs-6" id="username" name="username" placeholder="Ingrese número de documento">
      </div>
      <div class="form-group">
        <label for="password" class="form-label mt-4">Contraseña por defecto</label>
        <input type="password" required maxlength="20" class="form-control fs-6" aria-describedby="passHelp" id="password" name="password">
        <small id="passHelp" class="form-text text-muted">El usuario podrá cambiar esta contraseña desde su perfil.</small>
      </div>
      <div class="form-group">
        <label for="nombre_usuario" class="form-label mt-4">Nombre y Apellido</label>
        <input type="text" required maxlength="100" class="form-control fs-6" id="nombre_usuario" name="nombre_usuario">
      </div>
      <div class="form-group">
        <label for="correo_usuario" class="form-label mt-4">Correo Electrónico</label>
        <input type="email" maxlength="60" class="form-control fs-6" id="correo_usuario" name="correo_usuario" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">Puede dejarlo vacío el usuario puede agregarlo después.</small>
      </div>
      <div class="form-group">
        <label for="telefono_usuario" class="form-label mt-4">Telefono</label>
        <input type="number" maxlength="10" max="9999999999" class="form-control fs-6" id="telefono_usuario" name="telefono_usuario" aria-describedby="telHelp">
        <small id="telHelp" class="form-text text-muted">Puede dejarlo vacío, el usuario puede agregarlo después.</small>
      </div>
      <div class="dropdown-divider mt-3 mb-3"></div>
      <legend class="fs-5 text-center">Preferencias</legend>  
      <div class="dropdown-divider mt-3 mb-3"></div>
      <div class="form-group">
        <label for="rol_usuario" class="form-label mt-4">Rol del Usuario</label>
        <select required class="form-select fs-6" id="rol_usuario" name="rol_usuario"> 
          <option value="">-- Seleccione --</option>
          <option value="1">Administrador</option>
          <option value="2">Consultante</option>
        </select>
      </div>
      <div class="form-group">
        <label for="estado_usuario" class="form-label mt-4">Estado en el sistema</label>
        <select required class="form-select fs-6" id="estado_usuario" name="estado_usuario">
          <option value="">-- Seleccione --</option>
          <option value="1">Activo</option>
          <option value="0">Inactivo</option>
        </select>
      </div>
      <div class="dropdown-divider mt-4 mb-4"></div>
      <fieldset class="form-group mt-3 mb-3 text-center">
        <button type="submit" class="btn btn-light fs-6 p-3 ps-5 pe-5 w-auto">Guardar Usuario</button>
      </fieldset>

  </form>

{% endblock %}

app/src/templates/editar_docs.html
{% extends './layout.html' %}

{% block title %}
    {{data.titulo}}
{% endblock %}

{% block nameuser %}
  {{ current_user.nombre_usuario }}
{% endblock %}

{% block body %}

<form class="w-50 pt-3 m-auto" method="post" action="/editar/archivo/{{documento.0}}/{{documento.6}}/{{documento.7}}/{{documento.3}}" autocomplete="off" enctype="multipart/form-data">
    <fieldset>
      <legend class="text-center">Actualizar Documento/Formato</legend>
      <div class="dropdown-divider"></div>
      {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br>
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif%}
                {% endfor %}
            {% endif %}
        {% endwith %}
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div id="proceso_actual" style="display: inline;">
            <div class="form-group">
                <label for="carpeta" class="form-label mt-4">Macroproceso Actual</label>
                <div class="d-flex">
                    <input type="text" class="form-control fs-6" disabled id="carpeta" value="{{documento.1}}">
                    <!--<button type="button" onclick="show_carpetas()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>-->
                </div>
            </div>
            <div class="form-group">
                <label for="subcarpeta" class="form-label mt-4">Proceso Actual</label>
                <div class="d-flex">
                    <input type="text" class="form-control fs-6" disabled id="subcarpeta" value="{{documento.2}}">
                    <!-- <button type="button" onclick="show_carpetas()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>-->
                </div>
            </div>
        </div>
        <div id="procesos" style="display: none;">
            <div class="form-group">
                <label for="select_carpeta" class="form-label mt-4">Nuevo Macroproceso</label>
                <div class="d-flex">
                    <select class="form-select fs-6" id="select_carpeta" name="select_carpeta">
                    <option value="">-- Seleccione --</option>
                    {% for carpeta in carpetas %}
                    <option value="{{carpeta.0}}">{{carpeta.1}}</option>
                    {% endfor %}
                    </select>
                    <button type="button" onclick="show_carpetas()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
                </div>
            </div>
            <div class="form-group">
                <label for="select_subcarpeta" class="form-label mt-4">Nuevo Proceso</label>
                <div class="d-flex">
                    <select class="form-select fs-6" id="select_subcarpeta" name="select_subcarpeta">
                        <option value="">-- Seleccione --</option>
                    </select>
                    <button type="button" onclick="show_carpetas()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
                </div>
            </div>
        </div>
        <div id="archivo_actual" style="display: inline;" class="form-group">
            <label for="actual" class="form-label mt-4">Documento Actual</label>
            <div class="d-flex">
                <a href="/static/archivos/{{documento.6}}/{{documento.7}}/{{documento.3}}" class="w-100 text-decoration-none" download="download" title="Descargar Archivo">
                    <input type="text" style="cursor: pointer;" class="form-control fs-6 fs-bold" disabled id="actual" value="{{documento.3}}">
                </a>
                <button type="button" onclick="show_archivo()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
            </div>
        </div>
        <div class="form-group" style="display: none;" id="cont_archivo">
            <label for="archivo" class="form-label mt-4">Nuevo Documento</label>
            <div class="d-flex">
                <input class="form-control fs-6" type="file" id="archivo" name="archivo" aria-describedby="helpfile">
                <button type="button" onclick="show_archivo()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
            </div>
            <small id="helpfile" class="form-text text-muted">Asegurese de nombrar correctamente el archivo, ya que se mostrará en el sistema.</small>
        </div>
        <div class="form-group" id="fecha_actual" style="display: inline;">
            <label for="factual" class="form-label mt-4">Fecha Registrada</label>
            <div class="d-flex">
                <input type="text" class="form-control fs-6" disabled id="factual" value="{{documento.4.strftime('%d/%m/%Y')}}">
                <button type="button" onclick="show_fecha()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
            </div>
        </div>
        <div class="form-group" id="cont_fecha" style="display: none;">
            <label for="factual" class="form-label mt-4">Nueva Fecha</label>
            <div class="d-flex">
                <input type="date" class="form-control fs-6" id="fecha_archivo" name="fecha_archivo" value="{{documento.4}}" max="{{hoy}}" aria-describedby="helpfecha">
                <button type="button" onclick="show_fecha()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
            </div>
        </div>
        <div class="form-group" id="estado_actual" style="display: inline;">
            <label for="estado" class="form-label mt-4">Estado Actual</label>
            <div class="d-flex">
                <input type="text" class="form-control fs-6" disabled id="estado" value="{%if documento.8 == 1 %} Activo {% else %} Inactivo {% endif %}">
                <button type="button" onclick="show_estado()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
            </div>
        </div>
        <div class="form-group" id="cont_estado" style="display: none;">
            <label for="select_estado" class="form-label mt-4">Nuevo Estado</label>
            <div class="d-flex">
                <select class="form-select fs-6" id="select_estado" name="select_estado" aria-describedby="helpestado">
                <option value="">-- Seleccione --</option>
                <option value="1">Activo</option>
                <option value="0">Inactivo</option>
                </select>
                <button type="button" onclick="show_estado()" class="btn btn-info ms-1 btn-sm" title="Cambiar"><i class="fa-solid fa-arrow-rotate-right"></i></button>
            </div>
            <small id="helpestado" class="form-text text-muted">Los documentos activos son publicados automáticamente.</small>
          </div>
          <div class="form-group mt-4 row">
            <label for="version" class="col-sm-2 col-form-label">Versión</label>
            <div class="col-sm-10">
              <input type="text" readonly="" class="form-control-plaintext" id="version" name="version" value="{{documento.5}}">
            </div>
          </div>
      
      <div class="dropdown-divider mt-4 mb-4"></div>
      <fieldset class="form-group mt-3 mb-3 text-center">
        <button type="submit" class="btn btn-light fs-6 p-3 ps-5 pe-5 w-auto">Actualizar Documento</button>
        <a type="a" href="/actualizar" class="btn btn-light fs-6 p-3 ps-5 pe-5 w-auto">Volver</a>
    </fieldset>


  </form>

  <script>
    select_carpeta = document.getElementById('select_carpeta')
    select_subcarpeta = document.getElementById('select_subcarpeta')

    select_carpeta.onchange = function(){
        carpeta = select_carpeta.value;
        fetch('subcarpeta/'+carpeta).then(function(response){
            response.json().then(function(data){
                opcionHTML = '<option value="">-- Seleccione --</option>'
                for (subproceso of data.subprocesos){
                    opcionHTML += '<option value="'+subproceso.id+'">'+subproceso.nombre+'</option>'
                }
                select_subcarpeta.innerHTML = opcionHTML
            })
        })
    }


    function show_carpetas(){
        const procesos = document.getElementById('procesos')
        const proceso_actual = document.getElementById('proceso_actual')
        if (procesos.style.display == 'none'){
            procesos.style.display = 'inline'
            proceso_actual.style.display = 'none'
            document.getElementById('select_carpeta').setAttribute('required','')
            document.getElementById('select_subcarpeta').setAttribute('required','')
        }else{
            procesos.style.display = 'none'
            proceso_actual.style.display = 'inline'
            document.getElementById('select_carpeta').removeAttribute('required')
            document.getElementById('select_subcarpeta').removeAttribute('required')
        }
    }

    function show_archivo(){
        const arch = document.getElementById('cont_archivo')
        const actual = document.getElementById('archivo_actual')
        if (arch.style.display == 'none'){
            arch.style.display = 'inline'
            actual.style.display = 'none'
            document.getElementById('archivo').setAttribute('required','')
        }else{
            arch.style.display = 'none'
            actual.style.display = 'inline'
            document.getElementById('archivo').removeAttribute('required')
        }
    }

    function show_estado(){
        const estado = document.getElementById('cont_estado')
        const estado_actual = document.getElementById('estado_actual')
        if (estado.style.display == 'none'){
            estado.style.display = 'inline'
            estado_actual.style.display = 'none'
            document.getElementById('select_estado').setAttribute('required','')
        }else{
            estado.style.display = 'none'
            estado_actual.style.display = 'inline'
            document.getElementById('select_estado').removeAttribute('required')
        }
    }

    function show_fecha(){
        const fecha = document.getElementById('cont_fecha')
        const fecha_actual = document.getElementById('fecha_actual')
        if (fecha.style.display == 'none'){
            fecha.style.display = 'inline'
            fecha_actual.style.display = 'none'
            document.getElementById('fecha_archivo').setAttribute('required','')
        }else{
            fecha.style.display = 'none'
            fecha_actual.style.display = 'inline'
            document.getElementById('fecha_archivo').removeAttribute('required')
        }
    }
  </script>

{% endblock %}

app/src/templates/editar_perfil.html
{% extends './layout.html' %}

{% block title %}
    {{data.titulo}}
{% endblock %}

{% block nameuser %}
  {{ current_user.nombre_usuario }}
{% endblock %}

{% block body %}

<form class="w-50 pt-3 m-auto" method="post" action="/editar/perfil/{{current_user.id}}" autocomplete="off">
    <fieldset>
      <legend class="text-center">Editar Información de Perfil</legend>
      <div class="dropdown-divider"></div>
      {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br>
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif%}
                {% endfor %}
            {% endif %}
        {% endwith %}
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="form-group row">
        <label for="username" class="col-sm-2 col-form-label">Usuario</label>
        <div class="col-sm-10">
          <input type="text" readonly="" class="form-control-plaintext fs-6" id="username" value="{{ current_user.username }}" disabled>
        </div>
      </div>
      <div class="form-group">
        <label for="nombre_usuario" class="form-label mt-4">Nombre y Apellido</label>
        <input type="text" required maxlength="100" class="form-control fs-6" id="nombre_usuario" name="nombre_usuario" placeholder="Ingrese su nombre y apellido" value="{{ current_user.nombre_usuario }}">
        <label for="correo_usuario" class="form-label mt-4">Correo Electrónico</label>
        <input type="email" required maxlength="60" class="form-control fs-6" id="correo_usuario" name="correo_usuario" aria-describedby="emailHelp" placeholder="Ingrese su correo electrónico" value="{{ current_user.correo_usuario }}">
        <label for="telefono_usuario" class="form-label mt-4">Telefono</label>
        <input type="number" required maxlength="10" max="9999999999" class="form-control fs-6" id="telefono_usuario" name="telefono_usuario" placeholder="Ingrese su teléfono" value="{{ current_user.telefono_usuario }}">
        
        <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
      </div>
      <div class="dropdown-divider mt-3 mb-3"></div>
      <div class="form-group row">
        <label for="rol_usuario" class="col-sm-2 col-form-label">Rol</label>
        <div class="col-sm-10">
        {% if current_user.rol_usuario == 1 %}
          <input type="text" readonly="" class="form-control-plaintext fs-6" id="rol_usuario" value="Administrador" disabled>
        {% else %}
          <input type="text" readonly="" class="form-control-plaintext fs-6" id="rol_usuario" value="Consultante" disabled>
        {% endif %}
        </div>

        <label for="estado_usuario" class="col-sm-2 col-form-label">Estado</label>
        <div class="col-sm-10">
        {% if current_user.estado_usuario == 1 %}
          <input type="text" readonly="" class="form-control-plaintext fs-6" id="estado_usuario" value="Activo" disabled>
        {% else %}
          <input type="text" readonly="" class="form-control-plaintext fs-6" id="estado_usuario" value="Inactivo" disabled>
        {% endif %}
        </div>
      </div>
      <div class="dropdown-divider mt-4 mb-4"></div>
      <fieldset class="form-group mt-3 mb-3 text-center">
        <button type="submit" class="btn btn-light fs-6 p-3 ps-5 pe-5 w-auto">Actualizar Datos</button>
      </fieldset>

  </form>

{% endblock %}

app/src/templates/error.html
{% extends './layout.html' %}

{% block title %}
    Página no encontrada
{% endblock %}

{% block body %}
    <div class="alert alert-danger mt-3 text-center fs-6" role="alert">
        La página solicitada no ha podido ser encontrada.
    </div>
  <button type="button" class="btn btn-secondary fs-6 d-flex align-items-center p-3" onclick="javascript:window.history.back(-1);return false;"><i class="fa-solid fa-arrow-left me-3"></i><span class="me-3">Volver</span></button>

{% endblock %}

app/src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{{ url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3077d3980c.js" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static',filename='img/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static',filename='img/favicon-16x16.png')}}">
    {% block head %}{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src="{{ url_for('static',filename='img/logo.webp')}}" alt="" width="100" height="56" class="d-inline-block align-text-middle">
            Conec7a
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link active" href="/">Inicio
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              {% if current_user.rol_usuario == 1 %}
              <li class="d-flex nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administración</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="/crear_usuario">Crear Usuario</a>
                    <a class="dropdown-item" href="/lista_usuarios">Usuarios Registrados</a>
                  </div>
              </li>
              <li class="d-flex nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Gestión de Documentos</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="/subir_doc">Subir Documentos</a>
                    <a class="dropdown-item" href="/actualizar">Actualizar Documentos</a>
                    <a class="dropdown-item" href="/historial">Historial de Cambios</a>
                  </div>
              </li>
              {% endif %}
            </ul>
            {% if current_user.id %}
            <form class="d-block d-sm-flex" action="/listado/search" method="post" autocomplete="off">
              <ul class="navbar-nav me-auto">
                <li class="d-flex nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% block nameuser %}{% endblock %}</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="/editar_perfil">Editar Perfil</a>
                    <a class="dropdown-item" href="/cambiar_pass">Cambiar Contraseña</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ url_for('ingreso.cerrar_sesion')}}">Cerrar Sesión</a>
                  </div>
              </li>
              </ul>
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <input class="form-control me-sm-2" type="text" placeholder="Buscar Archivo" name="search_input" required>
              <button class="btn btn-light my-2 my-sm-0 p-2 d-flex align-items-center me-3" type="submit"><i class="fa-solid fa-magnifying-glass me-3"></i><span>Buscar</span></button>  
            </form>
            {% endif %}
          </div>
        </div>
      </nav>

    <div class="container pt-4">
        {% block body %}
        {% endblock %}
    </div>

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-4 border-top navbar-dark bg-dark mt-auto">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="text-muted">© 2022 Conec7a SAS</span>
        </div>
    
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5">
          <li class="ms-3"><a class="text-muted" href="#"><i class="fs-3 fa-brands fa-twitter"><use xlink:href="#twitter"></use></i></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><i class="fs-3 fa-brands fa-instagram"><use xlink:href="#instagram"></use></i></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><i class="fs-3 fa-brands fa-facebook"></i><use xlink:href="#facebook"></use></i></a></li>
        </ul>
      </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>
</html>